# Generated by Django 4.1.1 on 2022-09-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='era@g.com', max_length=254),
            preserve_default=False,
        ),
    ]
