# Generated by Django 4.1.1 on 2022-09-11 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-added_on']},
        ),
        migrations.AddField(
            model_name='comment',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 11, 13, 31, 41, 786206, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
