# Generated by Django 4.1.1 on 2022-09-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_options_comment_added_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('mobile', models.FileField(blank=True, null=True, upload_to='images/mobile')),
                ('windows', models.FileField(blank=True, null=True, upload_to='images/windows')),
                ('description', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
    ]
